title: Tifig
email: tonisuter@me.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tifig.net" # the base hostname & protocol for your site
twitter_username: tonisuter
github_username:  tonisuter

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, Dockerfile]
gems:
  - octopress-autoprefixer

sass:
    style: :compressed
